services:
    minio:
        image: 'minio/minio:latest'
        ports:
            - '9000:9000'
            - '8900:8900'
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: password
        volumes:
            - 'minio:/data/minio'
        command: 'minio server /data/minio --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - curl
                - '-f'
                - 'http://localhost:9000/minio/health/live'
            retries: 3
            timeout: 5s
    kafka:
        image: apache/kafka-native
        ports:
          - "9092:9092"
        environment:
          # Configure listeners for both docker and host communication
          KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
          KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

          # Settings required for KRaft mode
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

          # Listener to use for broker-to-broker communication
          KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

          # Required for a single node cluster
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    kafka-ui:
        image: ghcr.io/kafbat/kafka-ui:latest
        ports:
          - 8080:8080
        environment:
          DYNAMIC_CONFIG_ENABLED: "true"
          KAFKA_CLUSTERS_0_NAME: local
          KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
        depends_on:
          - kafka
    spark:
        image: bitnami/spark:latest
        environment:
          - SPARK_MODE=master
          - SPARK_EXTRA_CLASSPATHS="/opt/spark/jars/hadoop-aws-3.3.2.jar:/opt/spark/jars/aws-java-sdk-bundle-1.11.1026.jar"
        ports:
          - "7077:7077"
          - "8081:8081"
        volumes:
          - ./spark_analysis.py:/opt/bitnami/spark/spark_analysis.py

volumes:
    minio:
        driver: local